name: CI
on:
  pull_request:
    branches: [master, test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build in Docker
        run: docker build -t filenest-api-build .
